### ISSUE TITLE
Unsupported API

### ISSUE THREAD

**Issue by Agaloth** [timbru31/ImmortalLogin#22]
26.02 01:41:19 [Server] WARN org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.15
26.02 01:41:19 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:261)
26.02 01:41:19 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130)
26.02 01:41:19 [Server] WARN at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337)
26.02 01:41:19 [Server] WARN at net.dev.pluginmanager.commands.PluginManagerCommand.onCommand(PluginManagerCommand.java:194)
26.02 01:41:19 [Server] WARN at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
26.02 01:41:19 [Server] WARN at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
26.02 01:41:19 [Server] WARN at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.handleCommand(PlayerConnection.java:1804)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1612)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006)
26.02 01:41:19 [Server] WARN at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929)
26.02 01:41:19 [Server] WARN at java.lang.Thread.run(Thread.java:748)

Server version: Paper version git-Paper-239 (MC: 1.14.4) (Implementing API version 1.14.4-R0.1-SNAPSHOT)

**Comment by timbru31** [comment]
Oh, I've increased the API version. I've sent you a link via private message on Spigot. Let me know if that version works.
